---
title: "test"
author: "Amie Thomas"
date: "2023-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
```


#load in dataset 
```{r}
art <- read_dta("nanda_artsentrec_tract_2003-2017_01P.dta") #art/entertainment
```

#use only 2017 because it has the most up to date information for analysis and also to make computation easier. Getting rid of uninformative columns
```{r}
art_17 <- art|>
  filter(year == "2017")|>
  select(tract_fips10, year, population, count_7111, popden_7111, count_7112, popden_7112, count_712, popden_712,
         count_51912, popden_51912, count_7131, popden_7131, count_7132, popden_7132, count_7139, popden_7139, count_71394,
         popden_71394)
```

#check for 0's and handle
```{r}
missing_values <- any(is.na(art_17))
rows_with_missing <- art_17[!complete.cases(art_17), ]
#some census tracts have a 0 population. Can't do anything with this information so best to remove
#are these true 0's? Possible limitations in the data 

art_17_filt <- art_17 |>
  filter(population != 0) #no need for population of 0

miss_again <- any(is.na(art_17_filt)) #no missing values now

```

```{r}
#Northeast (Region 1):
# Connecticut: State Code - 09
# Maine: State Code - 23
# Massachusetts: State Code - 25
# New Hampshire: State Code - 33
# Rhode Island: State Code - 44
# Vermont: State Code - 50
# New Jersey: State Code - 34
# New York: State Code - 36
# Pennsylvania: State Code - 42


#Midwest (Region 2):
# Illinois: State Code - 17
# Indiana: State Code - 18
# Michigan: State Code - 26
# Ohio: State Code - 39
# Wisconsin: State Code - 55
# Iowa: State Code - 19
# Kansas: State Code - 20
# Minnesota: State Code - 27
# Missouri: State Code - 29
# Nebraska: State Code - 31
# North Dakota: State Code - 38
# South Dakota: State Code - 46


#South (Region 3):
# Delaware: State Code - 10
# Florida: State Code - 12
# Georgia: State Code - 13
# Maryland: State Code - 24
# North Carolina: State Code - 37
# South Carolina: State Code - 45
# Virginia: State Code - 51
# West Virginia: State Code - 54
# Alabama: State Code - 01
# Kentucky: State Code - 21
# Mississippi: State Code - 28
# Tennessee: State Code - 47
# Arkansas: State Code - 05
# Louisiana: State Code - 22
# Oklahoma: State Code - 40
# Texas: State Code - 48

#West (Region 4)
# Arizona: State Code - 04
# Colorado: State Code - 08
# Idaho: State Code - 16
# Montana: State Code - 30
# Nevada: State Code - 32
# New Mexico: State Code - 35
# Utah: State Code - 49
# Wyoming: State Code - 56
# Alaska: State Code - 02
# California: State Code - 06
# Hawaii: State Code - 15
# Oregon: State Code - 41
# Washington: State Code - 53
```

```{r}

get_census_region <- function(code) {
  census_region_map <- c(
    "10" = "South", "12" = "South", "13" = "South", "24" = "South", 
    "37" = "South", "45" = "South", "51" = "South", "54" = "South", 
    "01" = "South", "21" = "South", "28" = "South", "47" = "South", 
    "05" = "South", "22" = "South", "40" = "South", "48" = "South", 
    "09" = "Northeast", "23" = "Northeast", "25" = "Northeast", 
    "33" = "Northeast", "44" = "Northeast", "50" = "Northeast", 
    "34" = "Northeast", "36" = "Northeast", "42" = "Northeast", 
    "17" = "Midwest", "18" = "Midwest", "26" = "Midwest", "39" = "Midwest", 
    "55" = "Midwest", "19" = "Midwest", "20" = "Midwest", "27" = "Midwest", 
    "29" = "Midwest", "31" = "Midwest", "38" = "Midwest", "46" = "Midwest", 
    "04" = "West", "08" = "West", "16" = "West", "30" = "West", 
    "32" = "West", "35" = "West", "49" = "West", "56" = "West", 
    "02" = "West", "06" = "West", "15" = "West", "41" = "West", "53" = "West"
  )
  
  region <- census_region_map[substr(code, 1, 2)]
  if (is.na(region)) {
    region <- "Unknown"  
  }
  
  return(region)
}

art_17_filt <- art_17_filt |>
  mutate(census_region = sapply(tract_fips10, get_census_region))

art_17_filt <- art_17_filt |>
  relocate(census_region, .after = tract_fips10)

unknown_regions <- art_17_filt %>%
  filter(census_region == "Unknown")

#all of the tract codes are matched to their respective regions. There are 179 unknowns which don't make sense since all of them should have a match. Upon further inspection, the issue is the code begininng with 11. There is no matching state for this. It turns out that this code is for Washington DC which is a federal district and not a state. 

#we will change these unknowns to correspond with "south" to reflect the actual census region that it is a part of 

# Update census_region for census tracts starting with "11" to be "South"
art_17_filt$census_region[startsWith(art_17_filt$tract_fips10, "11")] <- "South"

```






